# --- DUT PARAMETERS ---
DUT_WC = 6.0e9
DUT_WQ = 5.2e9
DUT_G = 200e6
DUT_T1 = 100e-9
DUT_T2_STAR = 100e-9


# --- GLOBAL BEHAVIOR ---
ADAPTIVE = True
TRANSMISSION_COUPLED = False


# --- RESONATOR SCAN ---
VNA_START_FREQ = 5.5e9
VNA_STOP_FREQ = 6.5e9
VNA_COARSE_SWEEP_POINTS = 101
VNA_DENSE_SWEEP_POINTS = 401
VNA_ADAPTIVE_SWEEP_POINTS = 25
VNA_ADAPTIVE_ITERATIONS = 3
VNA_IFBW = 1000
VNA_AVERAGES = 100
VNA_POWERS = [-100]; assert all(power <= 0 for power in VNA_POWERS)


# --- QUBIT SCAN ---
SG_START_FREQ = 4.5e9
SG_STOP_FREQ = 5.5e9
SG_COARSE_SWEEP_POINTS = 101
SG_DENSE_SWEEP_POINTS = 401
SG_ADAPTIVE_SWEEP_POINTS = 25
SG_ADAPTIVE_ITERATIONS = 3
SG_POWERS = [-90]; assert all(power <= 0 for power in SG_POWERS)


# --- RABI SCAN ---
RABI_START_TIME = 0e-9
RABI_STOP_TIME = 500e-9
RABI_COARSE_SWEEP_POINTS = 20
RABI_DENSE_SWEEP_POINTS = 101
RABI_ADAPTIVE_POINTS = 30
RABI_POWERS = [-80]; assert all(power <= 0 for power in RABI_POWERS)


# --- RAMSEY SCAN ---
RAMSEY_START_TIME = 0e-9
RAMSEY_STOP_TIME = 500e-9
RAMSEY_COARSE_SWEEP_POINTS = 20
RAMSEY_DENSE_SWEEP_POINTS = 101
RAMSEY_ADAPTIVE_POINTS = 40
RAMSEY_DETUNING = 10e6


# --- T1 RELAXATION ---
T1_START_TIME = 0e-9
T1_STOP_TIME = 500e-9
T1_DENSE_SWEEP_POINTS = 101


# --- SHFQC SETTINGS ---
SHFQC_IFBW = 1
SHFQC_AVERAGES = 1000
